title           : WORLD
description     : https://restcountries.eu 에서 나라 정보(코드, 수도, 이름, 대륙, 국가 전화번호)를 가져와 정보를 리스팅해주는 페이지입니다.
dataUrl         : https://restcountries.eu/rest/v2/all?fields=alpha2Code;capital;name;region;callingCodes
author:
  nickname  : ROKROKSS
  name      : 김형록
  url       : https://rokrokss.com
  email     : hyungrok.kim@kaist.ac.kr
  github    : q0115643
copyright_date : 2019
github_repo : https://github.com/q0115643/rest_countries
